-- ============================================================
-- Capstify — Production Data Import
-- Run this in Hostinger phpMyAdmin on database: u999157431_capstify
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Clear existing data (safe — products must go first due to FK)
TRUNCATE TABLE `products`;
TRUNCATE TABLE `categories`;

-- ── Categories ───────────────────────────────────────────────
INSERT INTO `categories` VALUES (1,'Truckers','truckers','Breathable foam-front truckers built for all-day wear.','https://images.unsplash.com/photo-1719934663694-41b6fdceb448?w=900&q=85&auto=format&fit=crop',1);
INSERT INTO `categories` VALUES (2,'Classic','classic','Timeless six-panel silhouettes in premium cotton twill.','https://images.unsplash.com/photo-1622445275576-721325763afe?w=900&q=85&auto=format&fit=crop',2);
INSERT INTO `categories` VALUES (3,'A Frame','a-frame','Structured five-panel A-frame caps with a crisp front.','https://images.unsplash.com/photo-1733127547242-42a2e7ac12bb?w=900&q=85&auto=format&fit=crop',3);
INSERT INTO `categories` VALUES (4,'Baseball','baseball','Curved-brim baseball caps — the everyday essential.','https://images.unsplash.com/photo-1715608069265-f38ff5d8f234?w=900&q=85&auto=format&fit=crop',4);
INSERT INTO `categories` VALUES (5,'Snapback','snapback','Flat-brim snapbacks with adjustable closure for any fit.','https://images.unsplash.com/photo-1483103068651-8ce44652c331?w=900&q=85&auto=format&fit=crop',5);

-- ── Products ─────────────────────────────────────────────────
INSERT INTO `products` VALUES (1,'Forest Ranger','forest-ranger',1,'Built for the trail and the street alike. Foam front, mesh back, and a leather patch that ages like fine timber. The cap that goes where you go.','{"specs":[{"label":"Material","value":"65% Cotton / 35% Polyester — Mesh: 100% Polyester"},{"label":"Fit","value":"Unstructured, Mid Profile"},{"label":"Closure","value":"Adjustable Snapback"},{"label":"Brim","value":"Pre-Curved"},{"label":"Origin","value":"Made in Indonesia"}],"features":["Heat-pressed leather patch","Breathable 6-panel mesh back","Moisture-wicking sweatband","One size fits most"]}','["https://images.unsplash.com/photo-1719934663694-41b6fdceb448?w=900&q=85&auto=format&fit=crop","https://images.unsplash.com/photo-1719934663722-63b567d14eea?w=900&q=85&auto=format&fit=crop"]',275000,'Hi Capstify! I want to order the Forest Ranger Trucker Cap. Please let me know the availability and how to proceed.','','',1,1,1,'2026-05-06 20:18:30');
INSERT INTO `products` VALUES (2,'Maple Standard','maple-standard',1,'The clean trucker. A foam front that holds its shape, mesh back that breathes, and a woven patch that speaks for itself. No fuss.','{"specs":[{"label":"Material","value":"60% Cotton / 40% Polyester"},{"label":"Fit","value":"Structured, Mid Profile"},{"label":"Closure","value":"Adjustable Snapback"},{"label":"Brim","value":"Pre-Curved"},{"label":"Origin","value":"Made in Indonesia"}],"features":["Woven patch label","Ventilated 6-panel mesh back","Adjustable snapback closure","One size fits most"]}','["https://images.unsplash.com/photo-1719934663722-63b567d14eea?w=900&q=85&auto=format&fit=crop","https://images.unsplash.com/photo-1719934663694-41b6fdceb448?w=900&q=85&auto=format&fit=crop"]',250000,'Hi Capstify! I want to order the Maple Standard Trucker Cap. Please let me know the availability and how to proceed.','','',1,0,2,'2026-05-06 20:18:30');
INSERT INTO `products` VALUES (3,'The Signature','the-signature',2,'The six-panel cotton twill standard. Sits clean, wears clean, works everywhere from the corner store to the board room.','{"specs":[{"label":"Material","value":"100% Cotton Twill"},{"label":"Fit","value":"Structured, Mid Profile"},{"label":"Closure","value":"Adjustable Brass Buckle"},{"label":"Brim","value":"Pre-Curved"},{"label":"Origin","value":"Made in Indonesia"}],"features":["Six-panel construction","Tonal embroidered logo","Moisture-wicking sweatband","Brass buckle back strap"]}','["https://images.unsplash.com/photo-1622445275576-721325763afe?w=900&q=85&auto=format&fit=crop","https://images.unsplash.com/photo-1691256676359-20e5c6d4bc92?w=900&q=85&auto=format&fit=crop"]',290000,'Hi Capstify! I want to order The Signature Classic Cap. Please let me know the availability and how to proceed.','','',1,0,3,'2026-05-06 20:18:30');
INSERT INTO `products` VALUES (4,'Clean Slate','clean-slate',2,'Minimal. Structured. Ready for wherever the day takes you. The cap that lets your moves do the talking.','{"specs":[{"label":"Material","value":"100% Premium Cotton Twill"},{"label":"Fit","value":"Structured, Mid Profile"},{"label":"Closure","value":"Adjustable Snapback"},{"label":"Brim","value":"Pre-Curved"},{"label":"Origin","value":"Made in Indonesia"}],"features":["Clean front panel","Flat embroidered eyelets","Cotton sweatband","One size fits most"]}','["https://images.unsplash.com/photo-1691256676359-20e5c6d4bc92?w=900&q=85&auto=format&fit=crop","https://images.unsplash.com/photo-1622445275576-721325763afe?w=900&q=85&auto=format&fit=crop"]',265000,'Hi Capstify! I want to order the Clean Slate Classic Cap. Please let me know the availability and how to proceed.','','',0,1,4,'2026-05-06 20:18:30');
INSERT INTO `products` VALUES (5,'The Peak','the-peak',3,'Five panels, one intention: structured impact. The A-Frame silhouette sits sharp on any head and commands the room without trying.','{"specs":[{"label":"Material","value":"100% Cotton Drill"},{"label":"Fit","value":"Structured, Mid Profile"},{"label":"Closure","value":"Adjustable Fabric Strap"},{"label":"Brim","value":"Pre-Curved"},{"label":"Origin","value":"Made in Indonesia"}],"features":["Five-panel A-frame construction","Reinforced structured front","Woven label inside","One size fits most"]}','["https://images.unsplash.com/photo-1733127547242-42a2e7ac12bb?w=900&q=85&auto=format&fit=crop","https://images.unsplash.com/photo-1622445275576-721325763afe?w=900&q=85&auto=format&fit=crop"]',295000,'Hi Capstify! I want to order The Peak A Frame Cap. Please let me know the availability and how to proceed.','','',1,1,5,'2026-05-06 20:18:30');
INSERT INTO `products` VALUES (6,'Heritage A','heritage-a',3,'Vintage-washed canvas meets a sharp A-frame structure. A cap that looks better the more you wear it. Breaks in, never breaks down.','{"specs":[{"label":"Material","value":"100% Washed Cotton Canvas"},{"label":"Fit","value":"Unstructured, Low Profile"},{"label":"Closure","value":"Adjustable Leather Strap"},{"label":"Brim","value":"Slightly Curved"},{"label":"Origin","value":"Made in Indonesia"}],"features":["Vintage wash finish","Leather strap with brass buckle","Canvas sweatband","Soft front panel"]}','["https://images.unsplash.com/photo-1733127547242-42a2e7ac12bb?w=900&q=85&auto=format&fit=crop"]',280000,'Hi Capstify! I want to order the Heritage A Cap. Please let me know the availability and how to proceed.','','',0,1,6,'2026-05-06 20:18:30');
INSERT INTO `products` VALUES (7,'The Everyday','the-everyday',4,'The curved-brim daily driver. Goes with everything, complements everyone. This is the one you reach for without thinking.','{"specs":[{"label":"Material","value":"100% Cotton Twill"},{"label":"Fit","value":"Structured, Mid Profile"},{"label":"Closure","value":"Adjustable Snapback"},{"label":"Brim","value":"Curved, 3.5 inches"},{"label":"Origin","value":"Made in Indonesia"}],"features":["Curved bill","Six-panel construction","Embroidered logo","Adjustable back closure"]}','["https://images.unsplash.com/photo-1715608069265-f38ff5d8f234?w=900&q=85&auto=format&fit=crop","https://images.unsplash.com/photo-1691256676359-20e5c6d4bc92?w=900&q=85&auto=format&fit=crop"]',260000,'Hi Capstify! I want to order The Everyday Baseball Cap. Please let me know the availability and how to proceed.','','',1,0,7,'2026-05-06 20:18:30');
INSERT INTO `products` VALUES (8,'Ball Game','ball-game',4,'Classic baseball DNA, modern cut. Low profile, clean finish, curved brim that dips just right. The cap that started it all.','{"specs":[{"label":"Material","value":"60% Cotton / 40% Polyester"},{"label":"Fit","value":"Structured, Low Profile"},{"label":"Closure","value":"Adjustable Hook & Loop"},{"label":"Brim","value":"Curved, 3.5 inches"},{"label":"Origin","value":"Made in Indonesia"}],"features":["Low-profile crown","Curved brim","Embroidered ventilation eyelets","One size fits most"]}','["https://images.unsplash.com/photo-1691256676359-20e5c6d4bc92?w=900&q=85&auto=format&fit=crop","https://images.unsplash.com/photo-1715608069265-f38ff5d8f234?w=900&q=85&auto=format&fit=crop"]',275000,'Hi Capstify! I want to order the Ball Game Baseball Cap. Please let me know the availability and how to proceed.','','',0,1,8,'2026-05-06 20:18:30');
INSERT INTO `products` VALUES (9,'Street Code','street-code',5,'Flat brim, bold statement. The snapback for those who move with intention. Wear it forward. Wear it proud.','{"specs":[{"label":"Material","value":"100% Cotton Twill"},{"label":"Fit","value":"Structured, High Profile"},{"label":"Closure","value":"Flat Snapback"},{"label":"Brim","value":"Flat, 3 inches"},{"label":"Origin","value":"Made in Indonesia"}],"features":["Flat brim","High-profile crown","Embroidered graphic","Adjustable snap closure"]}','["https://images.unsplash.com/photo-1483103068651-8ce44652c331?w=900&q=85&auto=format&fit=crop","https://images.unsplash.com/photo-1627733041826-77dd65dc5a19?w=900&q=85&auto=format&fit=crop"]',285000,'Hi Capstify! I want to order the Street Code Snapback Cap. Please let me know the availability and how to proceed.','','',1,1,9,'2026-05-06 20:18:30');
INSERT INTO `products` VALUES (10,'Monochrome','monochrome',5,'All black. All flat. All business. The snapback without compromise — one colorway, zero distractions.','{"specs":[{"label":"Material","value":"100% Wool Blend"},{"label":"Fit","value":"Structured, High Profile"},{"label":"Closure","value":"Plastic Snapback"},{"label":"Brim","value":"Flat, 3 inches"},{"label":"Origin","value":"Made in Indonesia"}],"features":["All-over tonal black","Flat brim","Embroidered tonal logo","One size fits most"]}','["https://images.unsplash.com/photo-1627733041826-77dd65dc5a19?w=900&q=85&auto=format&fit=crop","https://images.unsplash.com/photo-1483103068651-8ce44652c331?w=900&q=85&auto=format&fit=crop"]',270000,'Hi Capstify! I want to order the Monochrome Snapback Cap. Please let me know the availability and how to proceed.','','',0,0,10,'2026-05-06 20:18:30');

SET FOREIGN_KEY_CHECKS = 1;
